id: PFDDE4D7F
initial_creation_type: ocr
source_metadata:
  volumes:
    d4eb14f0679944e9a157051c419b82de:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ལྟུང་བ་བཅོ་ལྔ་པ།
      total_pages: 1953
      volume_number: 27
